[project]
name = "tuto-kubernetes"
version = "0.1.0"
description = "Kubernetes initiation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
]
