apiVersion: v1
kind: Service
metadata:
  name: api-test-service
spec:
  # C'est ici qu'on fait le lien avec le Deployment
  # Le service va rediriger le trafic vers TOUS les pods qui ont le label "app: api-test"
  selector:
    app: api-test
  
  # Type LoadBalancer : Demande à Docker Desktop (ou au Cloud) de fournir une IP externe
  type: LoadBalancer
  
  ports:
    - protocol: TCP
      port: 80         # Le port accessible depuis l'extérieur (ton navigateur)
      targetPort: 8000 # Le port à l'intérieur du conteneur (ton code Flask)